image: ghcr.io/espressomd/docker/ubuntu:ab5bc64f5c3cc7330952f8b3bf321270ca53960c

stages:
  - prepare
  - build
  - result

.global_job_template: &global_job_definition
  before_script:
    - git config --global --add safe.directory "${CI_PROJECT_DIR}"
  timeout: 1h
  interruptible: true
  rules:
    - if: '$CI_COMMIT_REF_NAME != "staging.tmp" && $CI_COMMIT_REF_NAME != "trying.tmp"'

.notification_job_template: &notification_job_definition
  <<: *global_job_definition
  image: ghcr.io/espressomd/docker/alpine:ab5bc64f5c3cc7330952f8b3bf321270ca53960c
  variables:
    GET_SOURCES_ATTEMPTS: 3
  dependencies: []
  timeout: 20m
  interruptible: false
  tags:
    - espresso
    - no-cuda

variables:
  GET_SOURCES_ATTEMPTS: 3
  CCACHE_DIR: /cache
  CCACHE_MAXSIZE: 100G
  with_ccache: 'true'

status_pending:
  <<: *notification_job_definition
  stage: prepare
  script: sh maintainer/gh_post_status.sh pending

maxset:
  <<: *global_job_definition
  stage: build
  variables:
     CC: 'gcc-14'
     CXX: 'g++-14'
     GCOV: 'gcov-14'
     with_cuda: 'false'
     myconfig: 'maxset'
     with_coverage: 'false'
     with_coverage_python: 'false'
     with_scafacos: 'true'
     with_walberla: 'true'
     with_stokesian_dynamics: 'true'
     with_nlopt: 'true'
     with_caliper: 'true'
     check_skip_long: 'true'
     cmake_params: '-D CMAKE_CXX_STANDARD=23 -D CMAKE_CXX_EXTENSIONS=OFF -D ESPRESSO_TEST_NP=8 -D ESPRESSO_TEST_NT=8'
  script:
    - bash maintainer/CI/build_cmake.sh
  tags:
    - espresso
    - no-cuda
    - numa
    - avx2

tutorials-samples-maxset:
  <<: *global_job_definition
  stage: build
  variables:
     CC: 'gcc-12'
     CXX: 'g++-12'
     GCOV: 'gcov-12'
     myconfig: 'maxset'
     with_cuda: 'true'
     with_coverage: 'false'
     with_coverage_python: 'false'
     with_scafacos: 'true'
     with_walberla: 'true'
     with_walberla_avx: 'true'
     with_stokesian_dynamics: 'true'
     make_check_unit_tests: 'false'
     make_check_python: 'false'
     make_check_tutorials: 'true'
     make_check_samples: 'true'
     make_check_benchmarks: 'true'
     test_timeout: '1200'
  script:
    - bash maintainer/CI/build_cmake.sh
  tags:
    - espresso
    - cuda
    - numa
    - avx2

status_success:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_post_status.sh success
  when: on_success

status_failure:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_post_status.sh failure
  when: on_failure

notify_success:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_close_issue.sh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success

notify_failure:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_create_issue.sh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_failure
