image: ghcr.io/espressomd/docker/ubuntu:3388b293a5e8a9b613b1bfa4220e54dfb4bff245

stages:
  - prepare
  - build
  - additional_checks
  - result

.global_job_template: &global_job_definition
  before_script:
    - git config --global --add safe.directory "${CI_PROJECT_DIR}"
  timeout: 1h
  interruptible: true
  rules:
    - if: '$CI_COMMIT_REF_NAME != "staging.tmp" && $CI_COMMIT_REF_NAME != "trying.tmp"'

.notification_job_template: &notification_job_definition
  <<: *global_job_definition
  image: ghcr.io/espressomd/docker/alpine:3388b293a5e8a9b613b1bfa4220e54dfb4bff245
  variables:
    GET_SOURCES_ATTEMPTS: 3
  dependencies: []
  timeout: 40m
  interruptible: false
  tags:
    - espresso
    - no-cuda

variables:
  GET_SOURCES_ATTEMPTS: 3
  CCACHE_DIR: /cache
  CCACHE_MAXSIZE: 100G
  with_ccache: 'true'

status_pending:
  <<: *notification_job_definition
  stage: prepare
  script: sh maintainer/gh_post_status.sh pending

maxset:
  <<: *global_job_definition
  stage: build
  variables:
     CC: 'gcc-14'
     CXX: 'g++-14'
     GCOV: 'gcov-14'
     with_cuda: 'false'
     myconfig: 'maxset'
     with_coverage: 'false'
     with_scafacos: 'false'
     with_walberla: 'false'
     with_stokesian_dynamics: 'false'
     with_caliper: 'false'
     check_skip_long: 'true'
     make_check_python: 'false'
  script:
    - bash maintainer/CI/build_cmake.sh
  tags:
    - espresso
    - no-cuda
    - numa
    - avx2

status_success:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_post_status.sh success
  when: on_success

status_failure:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_post_status.sh failure
  when: on_failure

notify_success:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_close_issue.sh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_success

notify_failure:
  <<: *notification_job_definition
  stage: result
  script: sh maintainer/gh_create_issue.sh
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: on_failure
