name: 'Build and check'
description: 'Build espresso and run checks'
runs:
  using: "composite"
  steps:
    - run: |
       pip3 --version
       pip3 install --upgrade pip
       pip3 --version
       pip3 install -v -c requirements.txt "cython<3.0" numpy scipy pkg-resources
      shell: bash
      if: runner.os == 'macOS'
