name: run tests

on:
  push:
  pull_request:

jobs:
  test-wsl:
    runs-on: windows-2019
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
    - name: Setup Ubuntu 20.04 WSL
      uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
    - name: Convert CRLF to LF on Windows
      shell: bash
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Configure WSL for ESPResSo
      shell: bash
      run: |
        wsl bash -c "sudo adduser --uid 1000 --home /home/espresso --shell /bin/bash --disabled-password --gecos \"\" espresso"
        wsl bash -c "pwd"
        wsl bash -c "cd /home/espresso; pwd"
        wsl bash -c "pwd"
    - name: Build and test ESPResSo
      shell: bash
      run: |
        wsl --user espresso bash -c "export srcdir=$(pwd); cd "${HOME}"; myconfig=maxset with_cuda=false test_timeout=600 bash maintainer/CI/build_cmake.sh"
