name: run tests

on:
  push:
  pull_request:

jobs:
  test-wsl:
    runs-on: windows-2019
    defaults:
      run:
        shell: wsl-bash {0}
    steps:
    - name: Setup Ubuntu 20.04 WSL
      uses: Vampire/setup-wsl@v1
      with:
        distribution: Ubuntu-20.04
    - name: Convert CRLF to LF on Windows
      shell: bash
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Configure WSL for ESPResSo
      shell: bash
      run: |
        wsl bash -c "sudo apt-get update && sudo apt-get --no-install-recommends -y install build-essential cmake cython3 libboost-dev libboost-serialization-dev libboost-mpi-dev libboost-filesystem-dev libboost-test-dev libfftw3-dev libhdf5-openmpi-dev libopenmpi-dev openmpi-bin python3 python3-dev python3-numpy python3-scipy python3-h5py python3-setuptools python3-vtk7"
        wsl bash -c "sudo adduser --uid 1000 --home /home/espresso --shell /bin/bash --disabled-password --gecos \"\" espresso"
        wsl bash -c "chown espresso:espresso ."
    - name: Build and test ESPResSo
      shell: bash
      run: |
        wsl --user espresso bash -c "myconfig=maxset with_cuda=false test_timeout=600 bash maintainer/CI/build_cmake.sh"
