name: run tests on mac

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: macos-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@main
    - name: Install ESPResSo dependencies
      run: |
       brew install boost boost-mpi fftw
       brew install hdf5-mpi
       pip3 install numpy cython vtk h5py scipy
    - name: Build and test ESPResSo
      run: |
        export myconfig=maxset with_cuda=false test_timeout=600
        bash maintainer/CI/build_cmake.sh
