on:
  push:

permissions:
  contents: read

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Setup EESSI
        uses: eessi/github-action-eessi@v3
        with:
          eessi_stack_version: "2023.06"
      - name: Show dependencies
        run: |
          module avail
