name: GitLab-CI

on:
  workflow_call:
    secrets:
      GITLAB_WRITE_API:
        required: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  trigger_pipeline:
    runs-on: ubuntu-24.04
    environment: mirror
    steps:
      - name: "process pull request event (fetch changes)"
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/checkout@main
        with:
          fetch-depth: 100
      - name: "process pull request event (push changes)"
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git push -f https://github:${{ secrets.GITLAB_WRITE_API }}@gitlab.icp.uni-stuttgart.de/jgrad/espresso.git HEAD:PR-${{ github.event.number }}
      - name: "process push event (fetch changes)"
        if: ${{ github.event_name == 'push' }}
        uses: actions/checkout@main
        with:
          fetch-depth: 100
      - name: "process push event (push changes)"
        if: ${{ github.event_name == 'push' }}
        run: |
          export token=${{ secrets.GITLAB_WRITE_API }}
          echo "length: ${#token} last char: ${token: -1}"
          git push -f https://github:${{ secrets.GITLAB_WRITE_API }}@gitlab.icp.uni-stuttgart.de/jgrad/espresso.git ${{ github.ref_name }}
      - name: "update commit status"
        shell: sh
        run: |
          curl -s "${{ github.api_url }}/repos/${{ github.repository }}/statuses/${{ github.sha }}?access_token=${{ github.token }}" -H "Content-Type: application/json" -X POST \
               -d "{\"state\": \"pending\", \"context\": \"ICP GitLab CI\", \"target_url\": \"https://gitlab.icp.uni-stuttgart.de/jgrad/espresso/commit/${{ github.sha }}/pipelines\"}"
