name: mirror

on:
  push:
  create:
  pull_request:
    types: [opened, synchronize]

jobs:
  GitLab:
    if: ${{ github.repository == 'jngrad/espresso' }}
    uses: ./.github/workflows/gitlab.yml
    permissions:
      contents: read
      statuses: write
    secrets:
      # https://github.com/orgs/community/discussions/25238#discussioncomment-3247035
      GITLAB_WRITE_API: ${{ secrets.GITLAB_WRITE_API }}
