name: ESPResSo tests
on:
  pull_request:
  push:
    branches:
jobs:
  testsuite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup EESSI
        uses: ./.github/actions/eessi/actions.yml
        with:
          eessi_stack_version: 2025.06
      - name: Remote login (for live debugging)
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
          limit-access-to-actor: true
      - name: Install dependencies
        run: |
          test "${RUNNER_ARCH}" = "X64" && module use /cvmfs/software.eessi.io/host_injections/${EESSI_VERSION}/software/linux/x86_64/amd/zen2/modules/all
