name: run tests on linux
on:
  push:
    branches: [ ci-linux ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/espressomd/docker/debian:3fd42369f84239b8c4f5d77067d404789c55ff44
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
      options: --cpus 1
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
