name: run tests

on:
  push:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  macos:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: macos
          save: ${{ github.ref == 'refs/heads/python' }}
      - name: Get runner specifications
        run: system_profiler SPHardwareDataType
      - id: toolchain
        run: |
         brew install boost boost-mpi fftw
         python3 -m venv venv
         . venv/bin/activate
         pip3 install -c requirements.txt "cython<3.0.10" numpy scipy packaging
         deactivate
         echo "clang_CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_OUTPUT
         echo "clang_CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_OUTPUT
        shell: bash
      - name: Build and check
        uses: ./.github/actions/build_and_check
        env:
          build_procs: 3
          check_procs: 3
          CC: ${{ steps.toolchain.outputs.clang_CC }}
          CXX: ${{ steps.toolchain.outputs.clang_CXX }}
          with_ccache: 'true'

