name: ESPResSo tests
on:
  pull_request:
  push:
    branches:
jobs:
  testsuite:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - name: Setup EESSI
        uses: ./.github/actions/eessi
        with:
          eessi_stack_version: 2025.06
      - name: Stash environment (for upterm)
        run: echo 'source "$BASH_ENV"' >> ~/.bash_profile
      - name: Remote login (for live debugging)
        uses: owenthereal/action-upterm@1fb3e12e145279e2d0f3b117197d9ba171a0d5d6 # v1 + node24 support
        with:
          detached: true
          limit-access-to-actor: true
      - name: Install dependencies
        run: |
          test "${RUNNER_ARCH}" = "X64" && module use /cvmfs/dev.eessi.io/espresso/versions/${EESSI_VERSION}/software/linux/x86_64/amd/zen2/modules/all
          module load ESPResSo/95f275aa2060714e5d5b6c36e39fd4a9b422eacf-foss-2025a
          module save espresso
