name: run tests on linux
on:
  push:
    branches: [ ci-linux ]
jobs:
  debian:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/espressomd/docker/debian:3fd42369f84239b8c4f5d77067d404789c55ff44
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
      options: --cpus 1 --user espresso:espresso
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Build and check
        uses: ./.github/actions/build_and_check
        with:
          asan: false
          ubsan: false
        env:
          myconfig: 'maxset'
          with_cuda: 'false'
          with_hdf5: 'true'
          with_fftw: 'true'
          with_gsl: 'false'
          with_scafacos: 'false'
          with_stokesian_dynamics: 'false'
          make_check_unit_tests: 'true'
          make_check_python: 'false'
