name: run tests

on:
  push:
  pull_request:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  macos:
    runs-on: macos-12
    if: false
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: macos
          save: ${{ ! startsWith(github.ref, 'refs/pull') }}
      - name: Setup Python environment
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.9'
      - name: Get runner specifications
        run: system_profiler SPHardwareDataType
      - name: Build and check
        uses: ./.github/actions/build_and_check
        env:
          build_procs: 3
          check_procs: 3
          with_ccache: 'true'

  debian:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/espressomd/docker/debian:f6cf74049a2521b2b5580d23d42c8290c5f7611e-base-layer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
      options: --cpus 2
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: debian
          save: ${{  startsWith(github.ref, 'refs/pull') }}
      - name: Setup Git environment
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Get runner specifications
        run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
      - name: Build and check
        uses: ./.github/actions/build_and_check
        env:
          build_procs: 2
          check_procs: 2
          myconfig: 'maxset'
          with_ccache: 'true'
          with_cuda: 'false'
          with_hdf5: 'true'
          with_fftw: 'true'
          with_gsl: 'false'
          with_scafacos: 'false'
          with_stokesian_dynamics: 'false'
          make_check_unit_tests: 'true'
          make_check_python: 'false'
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1

  ubuntu:
    runs-on: ubuntu-latest
    if: false
    container:
      image: ghcr.io/espressomd/docker/ubuntu-wo-dependencies:f6cf74049a2521b2b5580d23d42c8290c5f7611e-base-layer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.github_token }}
      options: --cpus 2
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ubuntu
          save: ${{ ! startsWith(github.ref, 'refs/pull') }}
      - name: Setup Git environment
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Get runner specifications
        run: lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
      - name: Build and check
        uses: ./.github/actions/build_and_check
        env:
          build_procs: 2
          check_procs: 2
          myconfig: 'maxset'
          with_ccache: 'true'
          with_cuda: 'false'
          with_hdf5: 'false'
          with_fftw: 'false'
          with_gsl: 'false'
          with_scafacos: 'false'
          with_stokesian_dynamics: 'false'
          make_check_unit_tests: 'false'
          make_check_python: 'false'
          OMPI_ALLOW_RUN_AS_ROOT: 1
          OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
