name: run tests on mac

on:
  push:

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  regular_check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Python environment
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.9'
      - name: Check without sanitizer
        uses: ./.github/actions/build_and_check
        with:
          asan: false
          ubsan: false

  sanitizer_check:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Python environment
        uses: actions/setup-python@v4.3.1
        with:
          python-version: '3.9'
      - name: Check with sanitizer
        uses: ./.github/actions/build_and_check
        with:
          asan: true
          ubsan: true

  deploy_docs:
    runs-on: ubuntu-20.04
    steps:
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v2
      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.GH_PAGES_SSH_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@main
      - name: Deploy documentation
        uses: ./.github/actions/deploy_docs
